name: annotate_my_genomes
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _r-mutex
  - argtable2
  - atk-1.0
  - bedtools
  - binutils_impl_linux-64
  - binutils_linux-64
  - bioconductor-seqlogo
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - clustalo
  - coreutils
  - curl
  - emboss
  - expat
  - fasta_ushuffle
  - feelnc
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - fribidi
  - gawk
  - gcc_impl_linux-64
  - gcc_linux-64
  - gdk-pixbuf
  - gettext
  - gffcompare
  - gffread
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - giflib
  - gmap
  - graphite2
  - graphviz
  - gsl
  - gtk2
  - gts
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - htslib
  - icu
  - jbig
  - jpeg
  - k8
  - kernel-headers_linux-64
  - keyutils
  - kmerinshort
  - krb5
  - ld_impl_linux-64
  - lerc
  - libblas
  - libcblas
  - libcurl
  - libdb
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgd
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - liblapack
  - libnghttp2
  - libnsl
  - libopenblas
  - libpng
  - librsvg
  - libsanitizer
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtiff
  - libtool
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzlib
  - lz4-c
  - make
  - minimap2
  - ncurses
  - numpy
  - openssl
  - pandas
  - pango
  - parallel
  - pcre
  - pcre2
  - perl
  - perl-aceperl
  - perl-algorithm-diff
  - perl-algorithm-munkres
  - perl-apache-test
  - perl-app-cpanminus
  - perl-appconfig
  - perl-array-compare
  - perl-autoloader
  - perl-base
  - perl-bio-asn1-entrezgene
  - perl-bio-featureio
  - perl-bio-phylo
  - perl-bio-samtools
  - perl-bioperl
  - perl-bioperl-core
  - perl-bioperl-run
  - perl-business-isbn
  - perl-business-isbn-data
  - perl-cache-cache
  - perl-capture-tiny
  - perl-carp
  - perl-cgi
  - perl-class-data-inheritable
  - perl-class-inspector
  - perl-class-load
  - perl-class-load-xs
  - perl-class-method-modifiers
  - perl-clone
  - perl-common-sense
  - perl-compress-raw-zlib
  - perl-constant
  - perl-convert-binary-c
  - perl-convert-binhex
  - perl-crypt-rc4
  - perl-data-dumper
  - perl-data-optlist
  - perl-data-stag
  - perl-date-format
  - perl-db-file
  - perl-dbd-sqlite
  - perl-dbi
  - perl-devel-globaldestruction
  - perl-devel-overloadinfo
  - perl-devel-stacktrace
  - perl-digest-hmac
  - perl-digest-md5
  - perl-digest-perl-md5
  - perl-digest-sha1
  - perl-dist-checkconflicts
  - perl-dynaloader
  - perl-email-date-format
  - perl-encode
  - perl-encode-locale
  - perl-error
  - perl-eval-closure
  - perl-exception-class
  - perl-exporter
  - perl-exporter-tiny
  - perl-extutils-makemaker
  - perl-file-listing
  - perl-file-path
  - perl-file-slurp-tiny
  - perl-file-sort
  - perl-file-temp
  - perl-file-which
  - perl-font-afm
  - perl-font-ttf
  - perl-gd
  - perl-getopt-long
  - perl-graph
  - perl-graphviz
  - perl-html-element-extended
  - perl-html-entities-numbered
  - perl-html-formatter
  - perl-html-parser
  - perl-html-tableextract
  - perl-html-tagset
  - perl-html-tidy
  - perl-html-tree
  - perl-html-treebuilder-xpath
  - perl-http-cookies
  - perl-http-daemon
  - perl-http-date
  - perl-http-message
  - perl-http-negotiate
  - perl-image-info
  - perl-image-size
  - perl-io-html
  - perl-io-sessiondata
  - perl-io-socket-ssl
  - perl-io-string
  - perl-io-stringy
  - perl-io-tty
  - perl-ipc-run
  - perl-ipc-sharelite
  - perl-jcode
  - perl-json
  - perl-json-xs
  - perl-libwww-perl
  - perl-libxml-perl
  - perl-list-moreutils
  - perl-list-moreutils-xs
  - perl-local-lib
  - perl-lwp-mediatypes
  - perl-lwp-protocol-https
  - perl-lwp-simple
  - perl-mailtools
  - perl-math-cdf
  - perl-math-derivative
  - perl-math-random
  - perl-math-spline
  - perl-mime-base64
  - perl-mime-lite
  - perl-mime-tools
  - perl-mime-types
  - perl-mldbm
  - perl-module-build
  - perl-module-implementation
  - perl-module-runtime
  - perl-module-runtime-conflicts
  - perl-moo
  - perl-moose
  - perl-mozilla-ca
  - perl-mro-compat
  - perl-net-http
  - perl-net-ssleay
  - perl-ntlm
  - perl-ole-storage_lite
  - perl-package-deprecationmanager
  - perl-package-stash
  - perl-package-stash-xs
  - perl-parallel-forkmanager
  - perl-params-util
  - perl-parent
  - perl-parse-recdescent
  - perl-pathtools
  - perl-pdf-api2
  - perl-postscript
  - perl-role-tiny
  - perl-scalar-list-utils
  - perl-set-scalar
  - perl-soap-lite
  - perl-socket
  - perl-sort-naturally
  - perl-spreadsheet-parseexcel
  - perl-spreadsheet-writeexcel
  - perl-statistics-descriptive
  - perl-storable
  - perl-sub-exporter
  - perl-sub-exporter-progressive
  - perl-sub-identify
  - perl-sub-install
  - perl-sub-name
  - perl-sub-quote
  - perl-sub-uplevel
  - perl-svg
  - perl-svg-graph
  - perl-task-weaken
  - perl-template-toolkit
  - perl-test-deep
  - perl-test-differences
  - perl-test-exception
  - perl-test-leaktrace
  - perl-test-most
  - perl-test-pod
  - perl-test-requiresinternet
  - perl-test-warn
  - perl-text-diff
  - perl-threaded
  - perl-tie-ixhash
  - perl-time-local
  - perl-timedate
  - perl-tree-dag_node
  - perl-try-tiny
  - perl-type-tiny
  - perl-types-serialiser
  - perl-unicode-map
  - perl-uri
  - perl-www-robotrules
  - perl-xml-dom
  - perl-xml-dom-xpath
  - perl-xml-filter-buffertext
  - perl-xml-libxml
  - perl-xml-libxslt
  - perl-xml-namespacesupport
  - perl-xml-parser
  - perl-xml-regexp
  - perl-xml-sax
  - perl-xml-sax-base
  - perl-xml-sax-expat
  - perl-xml-sax-writer
  - perl-xml-simple
  - perl-xml-twig
  - perl-xml-writer
  - perl-xml-xpath
  - perl-xml-xpathengine
  - perl-xsloader
  - perl-yaml
  - pip
  - pixman
  - pthread-stubs
  - python
  - python-dateutil
  - python_abi
  - pytz
  - r-backports
  - r-base
  - r-bitops
  - r-brio
  - r-callr
  - r-catools
  - r-cli
  - r-colorspace
  - r-crayon
  - r-desc
  - r-diffobj
  - r-digest
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-farver
  - r-ggplot2
  - r-glue
  - r-gplots
  - r-gtable
  - r-gtools
  - r-isoband
  - r-jsonlite
  - r-kernsmooth
  - r-labeling
  - r-lattice
  - r-lifecycle
  - r-magrittr
  - r-mass
  - r-matrix
  - r-mgcv
  - r-munsell
  - r-nlme
  - r-pillar
  - r-pkgconfig
  - r-pkgload
  - r-praise
  - r-processx
  - r-ps
  - r-r6
  - r-randomforest
  - r-rcolorbrewer
  - r-rcpp
  - r-rematch2
  - r-rlang
  - r-rocr
  - r-rprojroot
  - r-rstudioapi
  - r-scales
  - r-testthat
  - r-tibble
  - r-utf8
  - r-vctrs
  - r-viridislite
  - r-waldo
  - r-withr
  - readline
  - seqkit
  - setuptools
  - six
  - sqlite
  - stringtie
  - sysroot_linux-64
  - tidyp
  - tk
  - tktable
  - transdecoder
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd
