name: annotate_my_genomes # name of environment
channels:
- bioconda
dependencies:             # everything under this, installed by conda
- parallel
- cufflinks
- stringtie
- gffcompare
- gffread
- gmap
- bedtools
- emboss
- clustalo 
- feelnc
- samtools
- minimap2
- transdecoder
