name: annotate_my_genomes # name of environment
channels:
- bioconda
- anaconda
- conda-forge
dependencies:             # everything under this, installed by conda
- python=3.6.13
- parallel
- cufflinks
- stringtie
- gffcompare
- gffread
- gmap
- bedtools
- emboss
- clustalo 
- feelnc
- samtools
- minimap2
- transdecoder
- seqkit
- gawk
- sed
