name: annotate_my_genomes # name of environment
channels:
- bioconda
dependencies:         # everything under this, installed by conda
- parallel
- cufflinks
- stringtie
- gffcompare
- gffread
- bioconda::blast=2.7.1
- gmap
- bedtools
- emboss
- clustalo
- agat 
- feelnc
- samtools
- r-car
- bioconductor-edger
- bioconductor-enhancedvolcano
